### ISSUE TITLE
生成的CSR请求无法使用

### ISSUE THREAD

**Issue by Chizaoyaowanla** [RangoW/skftool#1]
gmssl req -text -verify -in SS.usbkey.csr.pem 
verify failure
140250751803392:error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long:crypto/asn1/asn1_lib.c:101:
140250751803392:error:0D068066:asn1 encoding routines:asn1_check_tlen:bad object header:crypto/asn1/tasn_dec.c:1100:
140250751803392:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:274:Type=ECDSA_SIG
140250751803392:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:crypto/asn1/a_verify.c:188:
Certificate Request:
    Data:
        Version: 1 (0x0)
        Subject: 
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:31:ac:b6:43:8f:d5:02:96:bf:0b:f0:21:06:cf:
                    75:6c:b9:17:91:2f:fc:e3:a2:59:1a:86:70:22:2e:
                    14:ec:5e:63:93:3f:1e:99:0d:65:89:7a:4c:fc:0d:
                    c8:62:bb:33:77:31:18:59:78:27:61:23:27:18:b2:
                    96:5c:45:60:8b
                ASN1 OID: sm2p256v1
                NIST CURVE: SM2
        Attributes:
            a0:00
    Signature Algorithm: sm2sign-with-sm3
         7f:9e:b7:b8:2c:af:66:23:0f:56:37:a2:c3:6d:a8:39:90:ee:
         d7:1a:33:90:af:cf:af:f7:30:6d:6b:5e:1f:0b:9e:d6:1e:00:
         4c:a0:70:e5:39:bf:7a:d8:5a:ab:24:e2:26:21:be:86:1f:32:
         10:a7:0a:0d:19:a9:08:07:8c:c6
-----BEGIN CERTIFICATE REQUEST-----
MIGzMGICAQAwADBZMBMGByqGSM49AgEGCCqBHM9VAYItA0IABDGstkOP1QKWvwvw
IQbPdWy5F5Ev/OOiWRqGcCIuFOxeY5M/HpkNZYl6TPwNyGK7M3cxGFl4J2EjJxiy
llxFYIugADAKBggqgRzPVQGDdQNBAH+et7gsr2YjD1Y3osNtqDmQ7tcaM5Cvz6/3
MG1rXh8LntYeAEygcOU5v3rYWqsk4iYhvoYfMhCnCg0ZqQgHjMY=
-----END CERTIFICATE REQUEST-----

**Comment by xsmart** [comment]
一样的问题
verify failure
45140:error:0D07209B:asn1 encoding routines:ASN1_get_object:too long:crypto\asn1\asn1_lib.c:91:
45140:error:0D068066:asn1 encoding routines:asn1_check_tlen:bad object header:crypto\asn1\tasn_dec.c:1100:
45140:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:274:Type=ECDSA_SIG
45140:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:crypto\asn1\a_verify.c:188:
Certificate Request:
    Data:
        Version: 1 (0x0)
        Subject: CN = 34020000002000000001, C = CN, OU = Tech, O = 02
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:4e:cd:cf:e2:b0:47:ef:e7:28:43:48:91:af:d1:
                    35:fd:b0:39:95:e6:2e:18:56:1c:d1:c1:44:fc:0b:
                    1d:3b:65:46:71:65:b9:bb:fe:a1:de:54:9c:34:ec:
                    3f:f8:59:0b:42:84:97:33:7c:31:57:ae:6f:9c:5c:
                    6d:e7:2b:ae:6d
                ASN1 OID: sm2p256v1
                NIST CURVE: SM2
        Attributes:
            a0:00
    Signature Algorithm: sm2sign-with-sm3
         8f:78:21:79:93:97:91:b6:bf:d8:35:d5:8c:c7:97:db:6d:12:
         b1:5f:66:e3:7e:e6:8a:1a:bc:fb:cb:b0:11:c3:e9:df:74:cf:
         e9:5f:1e:4f:2c:68:9f:20:ca:e8:28:bf:83:67:6a:a6:87:81:
         8d:7b:2a:63:74:cb:67:ca:37:a4
-----BEGIN CERTIFICATE REQUEST-----
MIH8MIGqAgEAMEgxHTAbBgNVBAMMFDM0MDIwMDAwMDAyMDAwMDAwMDAxMQswCQYD
VQQGEwJDTjENMAsGA1UECwwEVGVjaDELMAkGA1UECgwCMDIwWTATBgcqhkjOPQIB
BggqgRzPVQGCLQNCAAROzc/isEfv5yhDSJGv0TX9sDmV5i4YVhzRwUT8Cx07ZUZx
Zbm7/qHeVJw07D/4WQtChJczfDFXrm+cXG3nK65toAAwCgYIKoEcz1UBg3UDQQCP
eCF5k5eRtr/YNdWMx5fbbRKxX2bjfuaKGrz7y7ARw+nfdM/pXx5PLGifIMroKL+D
Z2qmh4GNeypjdMtnyjek
-----END CERTIFICATE REQUEST-----

**Comment by RangoW** [comment]
> 一样的问题
> verify failure
> 45140:error:0D07209B:asn1 encoding routines:ASN1_get_object:too long:crypto\asn1\asn1_lib.c:91:
> 45140:error:0D068066:asn1 encoding routines:asn1_check_tlen:bad object header:crypto\asn1\tasn_dec.c:1100:
> 45140:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:274:Type=ECDSA_SIG
> 45140:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:crypto\asn1\a_verify.c:188:
> Certificate Request:
> Data:
> Version: 1 (0x0)
> Subject: CN = 34020000002000000001, C = CN, OU = Tech, O = 02
> Subject Public Key Info:
> Public Key Algorithm: id-ecPublicKey
> Public-Key: (256 bit)
> pub:
> 04:4e💿cf:e2:b0:47:ef:e7:28:43:48:91:af:d1:
> 35:fd:b0:39:95:e6:2e:18:56:1c:d1:c1:44:fc:0b:
> 1d:3b:65:46:71:65:b9:bb:fe:a1🇩🇪54:9c:34:ec:
> 3f:f8:59:0b:42:84:97:33:7c:31:57:ae:6f:9c:5c:
> 6d:e7:2b:ae:6d
> ASN1 OID: sm2p256v1
> NIST CURVE: SM2
> Attributes:
> a0:00
> Signature Algorithm: sm2sign-with-sm3
> 8f:78:21:79:93:97:91:b6:bf:d8:35:d5:8c:c7:97:db:6d:12:
> b1:5f:66:e3:7e:e6:8a:1a:bc:fb:cb:b0:11:c3:e9:df:74:cf:
> e9:5f:1e:4f:2c:68:9f:20:ca:e8:28:bf:83:67:6a:a6:87:81:
> 8d:7b:2a:63:74:cb:67:ca:37:a4
> -----BEGIN CERTIFICATE REQUEST-----
> MIH8MIGqAgEAMEgxHTAbBgNVBAMMFDM0MDIwMDAwMDAyMDAwMDAwMDAxMQswCQYD
> VQQGEwJDTjENMAsGA1UECwwEVGVjaDELMAkGA1UECgwCMDIwWTATBgcqhkjOPQIB
> BggqgRzPVQGCLQNCAAROzc/isEfv5yhDSJGv0TX9sDmV5i4YVhzRwUT8Cx07ZUZx
> Zbm7/qHeVJw07D/4WQtChJczfDFXrm+cXG3nK65toAAwCgYIKoEcz1UBg3UDQQCP
> eCF5k5eRtr/YNdWMx5fbbRKxX2bjfuaKGrz7y7ARw+nfdM/pXx5PLGifIMroKL+D
> Z2qmh4GNeypjdMtnyjek
> -----END CERTIFICATE REQUEST-----

my_pkey_meth_sign 函数签的摘要不对导致的。SM2 算法签名，需要对待签数据进行预处理操作， 漏掉了。

**Comment by Chizaoyaowanla** [comment]
@RangoW 大佬，这个对待签数据进行预处理操作具体是啥呢？可以透漏一下代码吗
