### ISSUE TITLE
使用USBKey进行双证书双向认证？

### ISSUE THREAD

**Issue by MobileAI** [RangoW/skftool#2]
想请教一下作者，后续有没有研究过使用USBKey和服务端之间进行双证书双向认证？SSL_CTX_use_PrivateKey_file() 将在文件中找到的第一个私钥添加到 SSL_CTX ctx。 证书的格式类型必须从已知类型 SSL_FILETYPE_PEM、SSL_FILETYPE_ASN1 中指定。USBKey无法导出私钥，如果有研究，麻烦赐教，谢谢

**Comment by RangoW** [comment]
如果要实现 tlcp 协议，可以通过代表私钥的容器句柄进行签名或加密。
如果只是借助 openssl 实现双向认证，可以使用 openssl engine 去调用 UKEY 。
比如：https://www.openssl.org/docs/man1.0.2/man3/engine.html
